name: Validate Pull Request

on:
  pull_request:
    branches:
      - stage
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 18.0.2.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate branch name
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} != feature/* ]]; then
            echo "Error: La rama del pull request no cumple con el formato 'feature/*'."
            exit 1
          fi

      - name: Run end-to-end tests
        run: |
          # Comandos para ejecutar pruebas

      - name: Build project
        run: |
          ./gradlew build --warning-mode all

      - name: Generate APK
        run: |
          # Comandos para generar el APK
          ./gradlew assembleDebug --warning-mode all

